apiVersion: v1
kind: Pod
metadata:
  name: GreenBlueTestDeploy
spec:
  imagePullSecrets:
    - name: acr-auth
    - name: acr-auth-front
  containers:
  - name: backend
    image: endavatalentbackend.azurecr.io/node-backend:testing-%GIT_TAG%
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi
    ports:
    - containerPort: 6200
      name: backend
  - name: frontend
    image: endavatalentfrontend.azurecr.io/react-frontend:testing-%GIT_TAG%
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi
    ports:
    - containerPort: 3000
      name: frontend
---

      