apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: endavatalentbackend.azurecr.io/node-backend:testing-%GIT_TAG%
        env:
        - name: MONGODB_URI
          value: "mongodb://10.1.112.23:27017/endava-talent-db?"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 6200
          name: backend
      imagePullSecrets:
      - name: acr-auth

