apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-persistence-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefilestorage
  resources:
    requests:
      storage: 5Gi
