apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: igonzalezend/endava-talent-qa:node-backend-testing-%GIT_TAG%
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 6200
          name: backend
      imagePullSecrets:
      - name: acr-auth
      volumes:
      - name: azurefileshare
        persistentVolumeClaim:
          claimName: dynamic-persistence-volume-claim

